### ISSUE TITLE
Badges and Logos

### ISSUE THREAD

**Issue by tunnckoCore** [standards/meta#1]
For each of the standards, some like `feross/standard`

[![js-standard-style](https://cdn.rawgit.com/feross/standard/master/badge.svg)](https://github.com/feross/standard)

``` markdown
[![js-standard-style](https://cdn.rawgit.com/feross/standard/master/badge.svg)](https://github.com/feross/standard)
```

and
[![js-semistandard-style](https://cdn.rawgit.com/flet/semistandard/master/badge.svg)](https://github.com/Flet/semistandard)

``` markdown
[![js-semistandard-style](https://cdn.rawgit.com/flet/semistandard/master/badge.svg)](https://github.com/Flet/semistandard)
```

And the badge for all can be simple like 

[![](https://img.shields.io/badge/code%20style-standard-brightgreen.svg)](https://img.shields.io/badge/code%20style-standard-brightgreen.svg)

``` markdown
[![](https://img.shields.io/badge/code%20style-standard-brightgreen.svg)](https://img.shields.io/badge/code%20style-standard-brightgreen.svg)
```

or for **CSS Standard Style**
[![](https://img.shields.io/badge/standard-css-brightgreen.svg)](https://img.shields.io/badge/standard-css-brightgreen.svg)

``` markdown
[![](https://img.shields.io/badge/standard-css-brightgreen.svg)](https://img.shields.io/badge/standard-css-brightgreen.svg)
```

 for **HTML Standard Style**
[![](https://img.shields.io/badge/standard-html-brightgreen.svg)](https://img.shields.io/badge/standard-html-brightgreen.svg)

``` markdown
[![](https://img.shields.io/badge/standard-html-brightgreen.svg)](https://img.shields.io/badge/standard-html-brightgreen.svg)
```

and etc

**Comment by leog** [comment]
@tunnckoCore I was thinking that we could potentially add a new GitHub integration to https://github.com/badges/shields in order to have a compelling badge, showing the version that is being complied and whether or not it's the latest version much like https://david-dm.org/ does. 

To make it more compelling, I was thinking that in order to avoid false badges we can rely on the validated GitHub Issue (see [Standard life cycle appendix]) for the integration on the shields project using labels.

That means that the badge image would be like:
```
https://img.shields.io/github/standards/<GITHUB_REPO>/<GITHUB_ISSUE_NUMBER>.svg
```
That should be enough to let the badge logic get the Git Issue, get the labels to:
1. look for the `validated` label to check it is a validated standard
2. use the `<GITHUB_REPO>` from the badge URL to use as the name
3. look for the `<VERSION-TO-VALIDATE>` on the Issue name to get the correspondent standard version that complies. The Issue name should be `Standard validation <VERSION-TO-VALIDATE>`.
4. look for the standard latest release to check whether the version that was complied is the latest to colorize the badge green otherwise red.

Note that the `<GITHUB_REPO>` on the badge URL needs to match to a Github Repository from the Standards organization, as any valid standard are located in that org. See [Standard life cycle appendix](https://standards.github.io/goto/standard-life-cycle) for more information.

This we can let the initiative control itself by the very usage of the badges consuming the very information that was put there by maintainers/validators on the Git Issues as described on the [Standard life cycle appendix].

[Standard life cycle appendix]: https://standards.github.io/goto/standard-life-cycle

**Comment by tunnckoCore** [comment]
Agreed, good idea.

**Comment by leog** [comment]
@tunnckoCore, please take a look at my implementation of the standards badge on shields
https://github.com/leog/shields/commit/91568e2771e6db79c17fe508ef76cc1fbb8bd858

This is how it looks:
![screenshot_010817_062917_pm](https://cloud.githubusercontent.com/assets/467258/21753646/60712c0a-d5d0-11e6-9e64-8590d2873ae6.jpg)

- the left part links to the standard and the second to the Issue
- the URL form is as above for the meta validation example: `github/standards/meta/4.svg`
- it does the checking against the version of the Git Issue located in the title with the standard latest release, that's why I created the v1.0.0 tag version for meta standard

If everything looks good, we can create a PR :+1:

**Comment by tunnckoCore** [comment]
It shows too much but okey... don't know, i'm pretty busy this month (university & courseworks).

**Comment by leog** [comment]
@tunnckoCore Ok, maybe this one looks better, simplified without the logo and lowercase:
![screenshot_010917_051828_pm](https://cloud.githubusercontent.com/assets/467258/21793162/b20c50e6-d6cd-11e6-9922-712004e6e97f.jpg)

**Comment by leog** [comment]
As decided we will be using a plain @badges/shields for now. A PR to support custom advanced badges for the initiative was submitted here https://github.com/badges/shields/pull/852. Closing for now.
